<?php

/**
 * Implements of hook_menu()
 */
function same_form_menu() {

}

/**
 * Implementation of hook_preprocess_page()
 */
function same_form_preprocess_page(&$variables) {

}

/**
 * Implementation of hook_preprocess_node()
 */
function same_form_preprocess_node(&$variables) {
  //var_dump($variables);exit;
  if($variables['type'] == 'form') {
    $fun_name_tpl = "_{$variables['type']}_template_data";
    $fun_name_data = "_{$variables['type']}_campaign_data";
    if(function_exists($fun_name_tpl) && function_exists($fun_name_data)) {
      $data = array('template_data' => $fun_name_tpl($variables['node']), 'campaign_data' => $fun_name_data($variables['node']));
      drupal_add_js($data, 'setting');
    }    
  }
}

function _form_template_data($node) {

  $template = node_load($node->field_form_template_id[LANGUAGE_NONE][0]['target_id']);

  $data = new stdClass();
  $data->logo = '';
  $data->backgound_color = '';
  $data->backgound_image = '';
  $data->button_color = '';

  if(isset($template->field_template_logo[LANGUAGE_NONE][0]['uri']))
    $data->logo = file_create_url($template->field_template_logo[LANGUAGE_NONE][0]['uri']);

  if(isset($template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"]))
    $data->backgound_color = $template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"];

  if(isset($template->field_template_bg_image[LANGUAGE_NONE][0]["uri"]))
    $data->backgound_image = file_create_url($template->field_template_bg_image[LANGUAGE_NONE][0]["uri"]);

  if(isset($template->field_template_btn_color[LANGUAGE_NONE][0]["rgb"]))
    $data->button_color = $template->field_template_btn_color[LANGUAGE_NONE][0]["rgb"];
 
  return $data;
}

function _form_campaign_data($node) {

  $form = new stdClass();
  $form->title = '';
  $form->body = array();
  $form->button_text = '';
  if(isset($node->field_page_button_text[LANGUAGE_NONE][0]['value']))
    $form->button_text = $node->field_page_button_text[LANGUAGE_NONE][0]['value'];
  foreach($node->field_form_fields[LANGUAGE_NONE] as $entity) {
    $entity = node_load($entity['target_id']);
    $field = new stdClass();
    $field->lable = $entity->title;
    $type = taxonomy_term_load($entity->field_form_field_type[LANGUAGE_NONE][0]['tid']);
    $field->type = $type->name;
    $field->name = $entity->field_form_field_name[LANGUAGE_NONE][0]['value'];
    $field->validate = isset($entity->field_form_field_validate[LANGUAGE_NONE][0]['value']) ? $entity->field_form_field_validate[LANGUAGE_NONE][0]['value'] : '0';
    $form->body[] = $field;
  }

  $successpage = new stdClass();
  $successpage->text = '';
  $successpage->button_text = '';
  $successpage->button_link = '';
  if(isset($node->field_form_success_page_text[LANGUAGE_NONE][0]['value']))
    $successpage->text = nl2br($node->field_form_success_page_text[LANGUAGE_NONE][0]['value']);
  if(isset($node->field_page_button_text[LANGUAGE_NONE][1]['value']))
    $successpage->button_text = $node->field_page_button_text[LANGUAGE_NONE][1]['value'];
  if(isset($node->field_page_forword_link[LANGUAGE_NONE][0]['url'])) {
    $successpage->button_link = $node->field_page_forword_link[LANGUAGE_NONE][0]['url'];
  }

  $data = new stdClass();
  $data->form = $form;
  $data->successpage = $successpage;
  $data->campaign = $node->nid;

  return $data;
}







