<?php

/**
 * Implements of hook_menu()
 */
function same_slideshow_menu() {

}

/**
 * Implementation of hook_preprocess_page()
 */
function same_slideshow_preprocess_page(&$variables) {

}

/**
 * Implementation of hook_preprocess_node()
 */
function same_slideshow_preprocess_node(&$variables) {
  if($variables['type'] == 'slideshow_a' || $variables['type'] == 'slideshow_b') {
    $fun_name_tpl = "_{$variables['type']}_template_data";
    $fun_name_data = "_{$variables['type']}_campaign_data";
    if(function_exists($fun_name_tpl) && function_exists($fun_name_data)) {
      $data = array('template_data' => $fun_name_tpl($variables['node']), 'campaign_data' => $fun_name_data($variables['node']));
      drupal_add_js($data, 'setting');
    }    
  }
}

function _slideshow_a_template_data($node) {

  $template = node_load($node->field_slideshow_a_template_id[LANGUAGE_NONE][0]['target_id']);

  $data = new stdClass();
  $data->logo = '';
  $data->backgound_color = '';
  $data->arrow_color = '';

  if(isset($template->field_template_logo[LANGUAGE_NONE][0]['uri']))
    $data->logo = file_create_url($template->field_template_logo[LANGUAGE_NONE][0]['uri']);

  if(isset($template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"]))
    $data->backgound_color = $template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"];

  if(isset($template->field_template_arrow_color[LANGUAGE_NONE][0]["rgb"]))
    $data->arrow_color = $template->field_template_arrow_color[LANGUAGE_NONE][0]["rgb"];
 
  return $data;
}

function _slideshow_a_campaign_data($node) {

  $data = array();

  foreach($node->field_slideshow_a[LANGUAGE_NONE] as $item) {
    $entity = field_collection_field_get_entity($item);
    $item = new stdClass();
    $item->thumbnail = image_style_url('slideshow_thumbnail', $entity->field_slideshow_a_thumb[LANGUAGE_NONE][0]['uri']);
    $item->picture = image_style_url('slideshow_pic', $entity->field_slideshow_a_pic[LANGUAGE_NONE][0]['uri']);

    $item->link = '';
    if(isset($entity->slideshow_a_link[LANGUAGE_NONE][0]['url']))
      $item->link = $entity->slideshow_a_link[LANGUAGE_NONE][0]['url'];
    $data[] = $item;
  }

  return $data;
}

function _slideshow_b_template_data($node) {

  $template = node_load($node->field_slideshow_b_template_id[LANGUAGE_NONE][0]['target_id']);

  $data = new stdClass();
  $data->logo = '';
  $data->backgound_color = '';
  $data->arrow_color = '';

  if(isset($template->field_template_logo[LANGUAGE_NONE][0]['uri']))
    $data->logo = file_create_url($template->field_template_logo[LANGUAGE_NONE][0]['uri']);

  if(isset($template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"]))
    $data->backgound_color = $template->field_template_bg_color[LANGUAGE_NONE][0]["rgb"];
  
  if(isset($template->field_template_arrow_color[LANGUAGE_NONE][0]["rgb"]))
    $data->arrow_color = $template->field_template_arrow_color[LANGUAGE_NONE][0]["rgb"];
 
  return $data;
}

function _slideshow_b_campaign_data($node) {

  $data = array();

  foreach($node->field_slideshow_b_pics[LANGUAGE_NONE] as $file) {
    $item = new stdClass();
    $item->picture = image_style_url('slideshow_pic', $file['uri']);
    $data[] = $item;
  }

  return $data;
}
